import Link from "next/link";

const content: Record<string, { title: string; intro: string; sections: [string, string][] }> = {
  about: { title: "About MasjidFinder", intro: "A practical network for the people and institutions that serve Muslim communities.", sections: [["What we connect", "Masjids, Imams, Huffaz, Qaris, Madrasas, teachers and scholars can discover one another across cities and countries."], ["What verification means", "A blue tick means our administrators reviewed submitted documents. It does not certify religious authority or guarantee a particular service."], ["Built for trust", "Private contact details remain protected until people choose to connect. Reports, blocks and moderation tools help keep the community useful."]] },
  "how-it-works": { title: "How it works", intro: "Find the right community connection in three clear steps.", sections: [["1. Search", "Choose a role, location or verified-only filter. Nearby search uses your browser location only when you explicitly allow it."], ["2. Review", "Open a profile or listing and check its roles, qualifications, availability and verification status."], ["3. Connect", "Send a request. Once accepted, the conversation appears in your inbox for real-time messaging."]] },
  contact: { title: "Contact", intro: "We are here to help with account, verification and marketplace questions.", sections: [["Account support", "Sign in and use your dashboard to review your profile, requests and notifications."], ["Verification", "Submit documents through the verification workflow. Administrators review requests in the queue."], ["Partnerships and feedback", "For support, partnerships or safety reports, email the address configured by the platform administrator."]] },
  faq: { title: "Frequently asked questions", intro: "Short answers to common questions.", sections: [["Is the blue tick religious certification?", "No. It confirms administrative document review only."], ["Can I search nearby?", "Yes. Use the location control on Search and allow the browser permission prompt. Coordinates are used to calculate nearby results."], ["How do connections work?", "A request must be accepted before private chat opens. You can block or report accounts from the relevant workflow."], ["How are shop orders paid?", "Orders are submitted for confirmation. The seller or platform team contacts you with payment and delivery details."]] },
  privacy: { title: "Privacy", intro: "MasjidFinder is designed to reveal only what is needed for discovery and connection.", sections: [["Public information", "Public cards contain display names, general locations, roles, qualifications and verification state. Phone numbers and exact addresses are not exposed through public views."], ["Account information", "Your account data is protected by Supabase authentication and row-level security. Chat is visible only to conversation participants."], ["Your choices", "You can edit your profile, block accounts and contact the platform about moderation or deletion requests."]] },
  terms: { title: "Terms", intro: "Use MasjidFinder respectfully and provide accurate information.", sections: [["Community conduct", "Do not impersonate people or institutions, misuse contact information, harass others or upload misleading documents."], ["Listings and shop", "You are responsible for the accuracy of listings and order details. Shop availability, price and delivery are confirmed by the seller or platform team."], ["Moderation", "Administrators may review reports, remove content, suspend accounts or remove verification when platform rules are not followed."]] },
};

export default function PublicPage({ slug }: { slug: keyof typeof content }) {
  const page = content[slug];
  return <main className="min-h-screen bg-sand-50 px-4 py-8 sm:px-6"><div className="mx-auto max-w-3xl"><Link href="/" className="text-sm font-semibold text-emerald-700">← Home</Link><header className="mt-12"><p className="text-xs font-bold uppercase tracking-[0.16em] text-gold-600">MasjidFinder</p><h1 className="mt-2 text-3xl font-semibold text-emerald-900">{page.title}</h1><p className="mt-3 text-lg text-ink-600">{page.intro}</p></header><section className="mt-10 divide-y divide-black/10 rounded-xl border border-black/10 bg-white px-5">{page.sections.map(([heading, body]) => <article key={heading} className="py-5"><h2 className="font-semibold text-emerald-900">{heading}</h2><p className="mt-2 text-sm leading-6 text-ink-600">{body}</p></article>)}</section></div></main>;
}