"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

const firqahs = ["sunni_hanafi", "sunni_shafii", "sunni_maliki", "sunni_hanbali", "salafi_ahle_hadith", "shia", "other", "prefer_not_to_say"];

export default function ProfilePage() {
  const router = useRouter(); const supabase = useMemo(() => createClient() as any, []);
  const [profile, setProfile] = useState<any>(null); const [error, setError] = useState<string | null>(null); const [saved, setSaved] = useState(false); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; supabase.auth.getUser().then(async ({ data }: any) => { if (!active) return; if (!data.user) { router.replace("/login"); return; } const result = await supabase.from("profiles").select("full_name, age, address_general, firqah").eq("id", data.user.id).single(); if (!active) return; if (result.error) setError(result.error.message); else setProfile(result.data); }); return () => { active = false; }; }, [router, supabase]);
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setSaved(false); const { error: saveError } = await supabase.from("profiles").update({ full_name: profile.full_name.trim(), age: Number(profile.age), address_general: profile.address.trim(), firqah: profile.firqah }).eq("id", (await supabase.auth.getUser()).data.user.id); setBusy(false); if (saveError) setError(saveError.message); else setSaved(true); }
  if (!profile) return <main className="p-6 text-sm text-ink-400">Loading profile…</main>;
  return <main className="min-h-screen bg-sand-50 p-6"><form onSubmit={save} className="max-w-lg mx-auto rounded-2xl border border-black/10 bg-white p-6"><h1 className="text-xl font-semibold text-emerald-900 mb-5">Edit profile</h1>{error && <p role="alert" className="mb-4 text-sm text-red-700">{error}</p>}{saved && <p className="mb-4 text-sm text-emerald-700">Profile updated.</p>}<label className="block text-sm font-semibold mb-3">Full name<input required value={profile.full_name} onChange={(event) => setProfile({ ...profile, full_name: event.target.value })} className="mt-1 w-full border rounded-lg p-3 font-normal" /></label><label className="block text-sm font-semibold mb-3">Age<input required type="number" min="15" max="110" value={profile.age ?? ""} onChange={(event) => setProfile({ ...profile, age: event.target.value })} className="mt-1 w-full border rounded-lg p-3 font-normal" /></label><label className="block text-sm font-semibold mb-3">Firqah / Maslak<select required value={profile.firqah ?? ""} onChange={(event) => setProfile({ ...profile, firqah: event.target.value })} className="mt-1 w-full border rounded-lg p-3 font-normal"><option value="">Select</option>{firqahs.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label><label className="block text-sm font-semibold mb-5">Address<input required value={profile.address_general ?? ""} onChange={(event) => setProfile({ ...profile, address_general: event.target.value })} className="mt-1 w-full border rounded-lg p-3 font-normal" /></label><div className="flex gap-2"><button type="button" onClick={() => router.push("/dashboard")} className="flex-1 rounded-lg border py-3 font-semibold">Back</button><button disabled={busy} className="flex-1 rounded-lg bg-emerald-900 py-3 font-semibold text-white disabled:opacity-50">{busy ? "Saving…" : "Save changes"}</button></div></form></main>;
}