"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

const firqahs = ["sunni_hanafi", "sunni_shafii", "sunni_maliki", "sunni_hanbali", "salafi_ahle_hadith", "shia", "other", "prefer_not_to_say"];

export default function ProfilePage() {
  const router = useRouter();
  const supabase = useMemo(() => createClient() as any, []);
  const [profile, setProfile] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; supabase.auth.getUser().then(async ({ data }: any) => { if (!active) return; if (!data.user) { router.replace("/login"); return; } const result = await supabase.from("profiles").select("full_name,age,address_general,firqah,profile_picture_url").eq("id", data.user.id).single(); if (!active) return; if (result.error) setError(result.error.message); else setProfile(result.data); }); return () => { active = false; }; }, [router, supabase]);
  async function uploadPicture(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/") || file.size > 5 * 1024 * 1024) { setError("Choose an image up to 5MB."); return; } setBusy(true); const { data: auth } = await supabase.auth.getUser(); const extension = file.name.split(".").pop() || "jpg"; const path = `${auth.user?.id}/profile-${Date.now()}.${extension}`; const upload = await supabase.storage.from("profile-pictures").upload(path, file, { contentType: file.type, upsert: true }); if (upload.error) setError(upload.error.message); else { const url = supabase.storage.from("profile-pictures").getPublicUrl(path).data.publicUrl; const result = await supabase.from("profiles").update({ profile_picture_url: url }).eq("id", auth.user?.id); if (result.error) setError(result.error.message); else setProfile((current: any) => ({ ...current, profile_picture_url: url })); } setBusy(false); }
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setSaved(false); const { error: saveError } = await supabase.from("profiles").update({ full_name: profile.full_name.trim(), age: Number(profile.age), address_general: profile.address_general.trim(), firqah: profile.firqah }).eq("id", (await supabase.auth.getUser()).data.user.id); setBusy(false); if (saveError) setError(saveError.message); else setSaved(true); }
  if (!profile) return <main className="p-6 text-sm text-ink-400">Loading profile…</main>;
  return <main className="min-h-screen bg-sand-50 p-6"><form onSubmit={save} className="mx-auto max-w-lg rounded-2xl border border-black/10 bg-white p-6"><h1 className="mb-5 text-xl font-semibold text-emerald-900">Edit profile</h1>{error && <p role="alert" className="mb-4 text-sm text-red-700">{error}</p>}{saved && <p className="mb-4 text-sm text-emerald-700">Profile updated.</p>}<label className="mb-5 flex items-center gap-4 text-sm font-semibold"><span className="flex h-20 w-20 items-center justify-center overflow-hidden rounded-full bg-sand-100 text-emerald-900">{profile.profile_picture_url ? <img src={profile.profile_picture_url} alt="Profile" className="h-full w-full object-cover" /> : "PFP"}</span><span>Profile picture<input type="file" accept="image/*" capture="user" onChange={uploadPicture} className="mt-2 block w-full text-xs font-normal" /></span></label><label className="mb-3 block text-sm font-semibold">Full name<input required value={profile.full_name} onChange={(event) => setProfile({ ...profile, full_name: event.target.value })} className="mt-1 w-full rounded-lg border p-3 font-normal" /></label><label className="mb-3 block text-sm font-semibold">Age<input required type="number" min="15" max="110" value={profile.age ?? ""} onChange={(event) => setProfile({ ...profile, age: event.target.value })} className="mt-1 w-full rounded-lg border p-3 font-normal" /></label><label className="mb-3 block text-sm font-semibold">Firqah / Maslak<select required value={profile.firqah ?? ""} onChange={(event) => setProfile({ ...profile, firqah: event.target.value })} className="mt-1 w-full rounded-lg border p-3 font-normal"><option value="">Select</option>{firqahs.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label><label className="mb-5 block text-sm font-semibold">Address<input required value={profile.address_general ?? ""} onChange={(event) => setProfile({ ...profile, address_general: event.target.value })} className="mt-1 w-full rounded-lg border p-3 font-normal" /></label><div className="flex gap-2"><button type="button" onClick={() => router.push("/dashboard")} className="flex-1 rounded-lg border py-3 font-semibold">Back</button><button disabled={busy} className="flex-1 rounded-lg bg-emerald-900 py-3 font-semibold text-white disabled:opacity-50">{busy ? "Saving…" : "Save changes"}</button></div></form></main>;
}
