"use client";

import { useState } from "react";

export default function ProfileActions({ recipientId, connectionId, connectionStatus, isRecipient }: { recipientId: string; connectionId: string | null; connectionStatus: string | null; isRecipient: boolean }) {
  const [status, setStatus] = useState(connectionStatus); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function requestConnection() { setBusy(true); setError(null); const response = await fetch("/api/connections", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ recipientId }) }); const result = await response.json(); setBusy(false); if (!response.ok) { setError(result.error ?? "Could not send request."); return; } setStatus(result.status); }
  async function acceptConnection() { if (!connectionId) return; setBusy(true); setError(null); const response = await fetch("/api/connections", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "accept", connectionId }) }); const result = await response.json(); setBusy(false); if (!response.ok) { setError(result.error ?? "Could not accept request."); return; } setStatus("accepted"); window.location.href = result.conversationId ? `/chat?conversation=${result.conversationId}` : "/chat"; }
  async function openChat() { if (!connectionId) return; const response = await fetch(`/api/connections?connectionId=${connectionId}`); const result = await response.json(); if (result.conversationId) window.location.href = `/chat?conversation=${result.conversationId}`; else setError("Chat is being prepared. Please try again."); }
  return <div className="min-w-[15rem] flex-1"><div className="flex flex-wrap gap-2">{status === "accepted" ? <><span className="inline-flex h-11 items-center rounded-lg bg-emerald-100 px-4 text-sm font-semibold text-emerald-800">Connected</span><button type="button" onClick={openChat} className="inline-flex h-11 items-center rounded-lg border border-emerald-900 px-4 text-sm font-semibold text-emerald-900">Chat</button></> : isRecipient && status === "pending" ? <button disabled={busy} onClick={acceptConnection} className="inline-flex h-11 items-center rounded-lg bg-emerald-900 px-4 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Accepting..." : "Accept and chat"}</button> : <button disabled={busy || Boolean(status)} onClick={requestConnection} className="inline-flex h-11 items-center rounded-lg bg-emerald-900 px-4 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Sending..." : status === "pending" ? "Request pending" : "Add friend"}</button>}</div>{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</div>;
}