"use client";

import { useState } from "react";

export default function ProfileActions({ recipientId, connectionId, connectionStatus, isRecipient }: { recipientId: string; connectionId: string | null; connectionStatus: string | null; isRecipient: boolean }) {
  const [status, setStatus] = useState(connectionStatus); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function requestConnection() { setBusy(true); setError(null); const response = await fetch("/api/connections", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ recipientId }) }); const result = await response.json(); setBusy(false); if (!response.ok) { setError(result.error ?? "Could not send request."); return; } setStatus(result.status); }
  async function acceptConnection() { if (!connectionId) return; setBusy(true); setError(null); const response = await fetch("/api/connections", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "accept", connectionId }) }); const result = await response.json(); setBusy(false); if (!response.ok) { setError(result.error ?? "Could not accept request."); return; } setStatus("accepted"); window.location.href = result.conversationId ? `/chat?conversation=${result.conversationId}` : "/chat"; }
  return <div className="mt-6 border-t border-black/10 pt-5"><div className="flex flex-wrap gap-2">{status === "accepted" ? <><span className="rounded-lg bg-emerald-100 px-4 py-3 text-sm font-semibold text-emerald-800">Connected</span><a href="/chat" className="rounded-lg border border-emerald-900 px-4 py-3 text-sm font-semibold text-emerald-900">Open chat</a></> : isRecipient && status === "pending" ? <button disabled={busy} onClick={acceptConnection} className="rounded-lg bg-emerald-900 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Accepting…" : "Accept and chat"}</button> : <button disabled={busy || Boolean(status)} onClick={requestConnection} className="rounded-lg bg-emerald-900 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Sending…" : status === "pending" ? "Request pending" : "Add friend"}</button>}</div>{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</div>;
}