"""
Generates supabase/seed/001_countries.sql from the COUNTRIES table below.
Run: python3 generate_countries_seed.py > 001_countries.sql

This is committed to the repo as a *generator* (not run at deploy time) so the
country list can be audited, diffed, and extended without hand-editing raw SQL.
The output SQL is what actually ships in supabase/seed/001_countries.sql.

Fields per country: (name, iso2, iso3, numeric, calling_code, currency_code,
                      currency_name, currency_symbol, timezone, flag_emoji, sort_order)
sort_order groups: 0 = major Muslim-majority / high-priority launch markets,
                    10 = rest of world, alphabetical fallback within group.
"""

COUNTRIES = [
("Afghanistan","AF","AFG","004","+93","AFN","Afghan Afghani","؋","Asia/Kabul","🇦🇫",0),
("Albania","AL","ALB","008","+355","ALL","Albanian Lek","L","Europe/Tirane","🇦🇱",10),
("Algeria","DZ","DZA","012","+213","DZD","Algerian Dinar","د.ج","Africa/Algiers","🇩🇿",0),
("Andorra","AD","AND","020","+376","EUR","Euro","€","Europe/Andorra","🇦🇩",10),
("Angola","AO","AGO","024","+244","AOA","Angolan Kwanza","Kz","Africa/Luanda","🇦🇴",10),
("Antigua and Barbuda","AG","ATG","028","+1268","XCD","East Caribbean Dollar","$","America/Antigua","🇦🇬",10),
("Argentina","AR","ARG","032","+54","ARS","Argentine Peso","$","America/Argentina/Buenos_Aires","🇦🇷",10),
("Armenia","AM","ARM","051","+374","AMD","Armenian Dram","֏","Asia/Yerevan","🇦🇲",10),
("Australia","AU","AUS","036","+61","AUD","Australian Dollar","$","Australia/Sydney","🇦🇺",10),
("Austria","AT","AUT","040","+43","EUR","Euro","€","Europe/Vienna","🇦🇹",10),
("Azerbaijan","AZ","AZE","031","+994","AZN","Azerbaijani Manat","₼","Asia/Baku","🇦🇿",0),
("Bahamas","BS","BHS","044","+1242","BSD","Bahamian Dollar","$","America/Nassau","🇧🇸",10),
("Bahrain","BH","BHR","048","+973","BHD","Bahraini Dinar",".د.ب","Asia/Bahrain","🇧🇭",0),
("Bangladesh","BD","BGD","050","+880","BDT","Bangladeshi Taka","৳","Asia/Dhaka","🇧🇩",0),
("Barbados","BB","BRB","052","+1246","BBD","Barbadian Dollar","$","America/Barbados","🇧🇧",10),
("Belarus","BY","BLR","112","+375","BYN","Belarusian Ruble","Br","Europe/Minsk","🇧🇾",10),
("Belgium","BE","BEL","056","+32","EUR","Euro","€","Europe/Brussels","🇧🇪",10),
("Belize","BZ","BLZ","084","+501","BZD","Belize Dollar","$","America/Belize","🇧🇿",10),
("Benin","BJ","BEN","204","+229","XOF","West African CFA Franc","Fr","Africa/Porto-Novo","🇧🇯",0),
("Bhutan","BT","BTN","064","+975","BTN","Bhutanese Ngultrum","Nu.","Asia/Thimphu","🇧🇹",10),
("Bolivia","BO","BOL","068","+591","BOB","Bolivian Boliviano","Bs.","America/La_Paz","🇧🇴",10),
("Bosnia and Herzegovina","BA","BIH","070","+387","BAM","Bosnia-Herzegovina Mark","КМ","Europe/Sarajevo","🇧🇦",0),
("Botswana","BW","BWA","072","+267","BWP","Botswana Pula","P","Africa/Gaborone","🇧🇼",10),
("Brazil","BR","BRA","076","+55","BRL","Brazilian Real","R$","America/Sao_Paulo","🇧🇷",10),
("Brunei","BN","BRN","096","+673","BND","Brunei Dollar","$","Asia/Brunei","🇧🇳",0),
("Bulgaria","BG","BGR","100","+359","BGN","Bulgarian Lev","лв","Europe/Sofia","🇧🇬",10),
("Burkina Faso","BF","BFA","854","+226","XOF","West African CFA Franc","Fr","Africa/Ouagadougou","🇧🇫",0),
("Burundi","BI","BDI","108","+257","BIF","Burundian Franc","Fr","Africa/Bujumbura","🇧🇮",10),
("Cabo Verde","CV","CPV","132","+238","CVE","Cape Verdean Escudo","$","Atlantic/Cape_Verde","🇨🇻",10),
("Cambodia","KH","KHM","116","+855","KHR","Cambodian Riel","៛","Asia/Phnom_Penh","🇰🇭",10),
("Cameroon","CM","CMR","120","+237","XAF","Central African CFA Franc","Fr","Africa/Douala","🇨🇲",10),
("Canada","CA","CAN","124","+1","CAD","Canadian Dollar","$","America/Toronto","🇨🇦",10),
("Central African Republic","CF","CAF","140","+236","XAF","Central African CFA Franc","Fr","Africa/Bangui","🇨🇫",10),
("Chad","TD","TCD","148","+235","XAF","Central African CFA Franc","Fr","Africa/Ndjamena","🇹🇩",0),
("Chile","CL","CHL","152","+56","CLP","Chilean Peso","$","America/Santiago","🇨🇱",10),
("China","CN","CHN","156","+86","CNY","Chinese Yuan","¥","Asia/Shanghai","🇨🇳",10),
("Colombia","CO","COL","170","+57","COP","Colombian Peso","$","America/Bogota","🇨🇴",10),
("Comoros","KM","COM","174","+269","KMF","Comorian Franc","Fr","Indian/Comoro","🇰🇲",0),
("Congo (DRC)","CD","COD","180","+243","CDF","Congolese Franc","Fr","Africa/Kinshasa","🇨🇩",10),
("Congo (Republic)","CG","COG","178","+242","XAF","Central African CFA Franc","Fr","Africa/Brazzaville","🇨🇬",10),
("Costa Rica","CR","CRI","188","+506","CRC","Costa Rican Colon","₡","America/Costa_Rica","🇨🇷",10),
("Cote d'Ivoire","CI","CIV","384","+225","XOF","West African CFA Franc","Fr","Africa/Abidjan","🇨🇮",10),
("Croatia","HR","HRV","191","+385","EUR","Euro","€","Europe/Zagreb","🇭🇷",10),
("Cuba","CU","CUB","192","+53","CUP","Cuban Peso","$","America/Havana","🇨🇺",10),
("Cyprus","CY","CYP","196","+357","EUR","Euro","€","Asia/Nicosia","🇨🇾",10),
("Czechia","CZ","CZE","203","+420","CZK","Czech Koruna","Kč","Europe/Prague","🇨🇿",10),
("Denmark","DK","DNK","208","+45","DKK","Danish Krone","kr","Europe/Copenhagen","🇩🇰",10),
("Djibouti","DJ","DJI","262","+253","DJF","Djiboutian Franc","Fr","Africa/Djibouti","🇩🇯",0),
("Dominica","DM","DMA","212","+1767","XCD","East Caribbean Dollar","$","America/Dominica","🇩🇲",10),
("Dominican Republic","DO","DOM","214","+1809","DOP","Dominican Peso","$","America/Santo_Domingo","🇩🇴",10),
("Ecuador","EC","ECU","218","+593","USD","US Dollar","$","America/Guayaquil","🇪🇨",10),
("Egypt","EG","EGY","818","+20","EGP","Egyptian Pound","£","Africa/Cairo","🇪🇬",0),
("El Salvador","SV","SLV","222","+503","USD","US Dollar","$","America/El_Salvador","🇸🇻",10),
("Equatorial Guinea","GQ","GNQ","226","+240","XAF","Central African CFA Franc","Fr","Africa/Malabo","🇬🇶",10),
("Eritrea","ER","ERI","232","+291","ERN","Eritrean Nakfa","Nfk","Africa/Asmara","🇪🇷",10),
("Estonia","EE","EST","233","+372","EUR","Euro","€","Europe/Tallinn","🇪🇪",10),
("Eswatini","SZ","SWZ","748","+268","SZL","Swazi Lilangeni","L","Africa/Mbabane","🇸🇿",10),
("Ethiopia","ET","ETH","231","+251","ETB","Ethiopian Birr","Br","Africa/Addis_Ababa","🇪🇹",10),
("Fiji","FJ","FJI","242","+679","FJD","Fijian Dollar","$","Pacific/Fiji","🇫🇯",10),
("Finland","FI","FIN","246","+358","EUR","Euro","€","Europe/Helsinki","🇫🇮",10),
("France","FR","FRA","250","+33","EUR","Euro","€","Europe/Paris","🇫🇷",10),
("Gabon","GA","GAB","266","+241","XAF","Central African CFA Franc","Fr","Africa/Libreville","🇬🇦",10),
("Gambia","GM","GMB","270","+220","GMD","Gambian Dalasi","D","Africa/Banjul","🇬🇲",0),
("Georgia","GE","GEO","268","+995","GEL","Georgian Lari","₾","Asia/Tbilisi","🇬🇪",10),
("Germany","DE","DEU","276","+49","EUR","Euro","€","Europe/Berlin","🇩🇪",10),
("Ghana","GH","GHA","288","+233","GHS","Ghanaian Cedi","₵","Africa/Accra","🇬🇭",10),
("Greece","GR","GRC","300","+30","EUR","Euro","€","Europe/Athens","🇬🇷",10),
("Grenada","GD","GRD","308","+1473","XCD","East Caribbean Dollar","$","America/Grenada","🇬🇩",10),
("Guatemala","GT","GTM","320","+502","GTQ","Guatemalan Quetzal","Q","America/Guatemala","🇬🇹",10),
("Guinea","GN","GIN","324","+224","GNF","Guinean Franc","Fr","Africa/Conakry","🇬🇳",0),
("Guinea-Bissau","GW","GNB","624","+245","XOF","West African CFA Franc","Fr","Africa/Bissau","🇬🇼",0),
("Guyana","GY","GUY","328","+592","GYD","Guyanese Dollar","$","America/Guyana","🇬🇾",10),
("Haiti","HT","HTI","332","+509","HTG","Haitian Gourde","G","America/Port-au-Prince","🇭🇹",10),
("Honduras","HN","HND","340","+504","HNL","Honduran Lempira","L","America/Tegucigalpa","🇭🇳",10),
("Hungary","HU","HUN","348","+36","HUF","Hungarian Forint","Ft","Europe/Budapest","🇭🇺",10),
("Iceland","IS","ISL","352","+354","ISK","Icelandic Krona","kr","Atlantic/Reykjavik","🇮🇸",10),
("India","IN","IND","356","+91","INR","Indian Rupee","₹","Asia/Kolkata","🇮🇳",0),
("Indonesia","ID","IDN","360","+62","IDR","Indonesian Rupiah","Rp","Asia/Jakarta","🇮🇩",0),
("Iran","IR","IRN","364","+98","IRR","Iranian Rial","﷼","Asia/Tehran","🇮🇷",0),
("Iraq","IQ","IRQ","368","+964","IQD","Iraqi Dinar","ع.د","Asia/Baghdad","🇮🇶",0),
("Ireland","IE","IRL","372","+353","EUR","Euro","€","Europe/Dublin","🇮🇪",10),
("Israel","IL","ISR","376","+972","ILS","Israeli New Shekel","₪","Asia/Jerusalem","🇮🇱",10),
("Italy","IT","ITA","380","+39","EUR","Euro","€","Europe/Rome","🇮🇹",10),
("Jamaica","JM","JAM","388","+1876","JMD","Jamaican Dollar","$","America/Jamaica","🇯🇲",10),
("Japan","JP","JPN","392","+81","JPY","Japanese Yen","¥","Asia/Tokyo","🇯🇵",10),
("Jordan","JO","JOR","400","+962","JOD","Jordanian Dinar","د.ا","Asia/Amman","🇯🇴",0),
("Kazakhstan","KZ","KAZ","398","+7","KZT","Kazakhstani Tenge","₸","Asia/Almaty","🇰🇿",0),
("Kenya","KE","KEN","404","+254","KES","Kenyan Shilling","Sh","Africa/Nairobi","🇰🇪",10),
("Kiribati","KI","KIR","296","+686","AUD","Australian Dollar","$","Pacific/Tarawa","🇰🇮",10),
("Kosovo","XK","XKX","","+383","EUR","Euro","€","Europe/Belgrade","🇽🇰",10),
("Kuwait","KW","KWT","414","+965","KWD","Kuwaiti Dinar","د.ك","Asia/Kuwait","🇰🇼",0),
("Kyrgyzstan","KG","KGZ","417","+996","KGS","Kyrgyzstani Som","с","Asia/Bishkek","🇰🇬",0),
("Laos","LA","LAO","418","+856","LAK","Lao Kip","₭","Asia/Vientiane","🇱🇦",10),
("Latvia","LV","LVA","428","+371","EUR","Euro","€","Europe/Riga","🇱🇻",10),
("Lebanon","LB","LBN","422","+961","LBP","Lebanese Pound","ل.ل","Asia/Beirut","🇱🇧",0),
("Lesotho","LS","LSO","426","+266","LSL","Lesotho Loti","L","Africa/Maseru","🇱🇸",10),
("Liberia","LR","LBR","430","+231","LRD","Liberian Dollar","$","Africa/Monrovia","🇱🇷",10),
("Libya","LY","LBY","434","+218","LYD","Libyan Dinar","ل.د","Africa/Tripoli","🇱🇾",0),
("Liechtenstein","LI","LIE","438","+423","CHF","Swiss Franc","Fr","Europe/Vaduz","🇱🇮",10),
("Lithuania","LT","LTU","440","+370","EUR","Euro","€","Europe/Vilnius","🇱🇹",10),
("Luxembourg","LU","LUX","442","+352","EUR","Euro","€","Europe/Luxembourg","🇱🇺",10),
("Madagascar","MG","MDG","450","+261","MGA","Malagasy Ariary","Ar","Indian/Antananarivo","🇲🇬",10),
("Malawi","MW","MWI","454","+265","MWK","Malawian Kwacha","MK","Africa/Blantyre","🇲🇼",10),
("Malaysia","MY","MYS","458","+60","MYR","Malaysian Ringgit","RM","Asia/Kuala_Lumpur","🇲🇾",0),
("Maldives","MV","MDV","462","+960","MVR","Maldivian Rufiyaa","ރ.","Indian/Maldives","🇲🇻",0),
("Mali","ML","MLI","466","+223","XOF","West African CFA Franc","Fr","Africa/Bamako","🇲🇱",0),
("Malta","MT","MLT","470","+356","EUR","Euro","€","Europe/Malta","🇲🇹",10),
("Marshall Islands","MH","MHL","584","+692","USD","US Dollar","$","Pacific/Majuro","🇲🇭",10),
("Mauritania","MR","MRT","478","+222","MRU","Mauritanian Ouguiya","UM","Africa/Nouakchott","🇲🇷",0),
("Mauritius","MU","MUS","480","+230","MUR","Mauritian Rupee","₨","Indian/Mauritius","🇲🇺",10),
("Mexico","MX","MEX","484","+52","MXN","Mexican Peso","$","America/Mexico_City","🇲🇽",10),
("Micronesia","FM","FSM","583","+691","USD","US Dollar","$","Pacific/Chuuk","🇫🇲",10),
("Moldova","MD","MDA","498","+373","MDL","Moldovan Leu","L","Europe/Chisinau","🇲🇩",10),
("Monaco","MC","MCO","492","+377","EUR","Euro","€","Europe/Monaco","🇲🇨",10),
("Mongolia","MN","MNG","496","+976","MNT","Mongolian Tugrik","₮","Asia/Ulaanbaatar","🇲🇳",10),
("Montenegro","ME","MNE","499","+382","EUR","Euro","€","Europe/Podgorica","🇲🇪",10),
("Morocco","MA","MAR","504","+212","MAD","Moroccan Dirham","د.م.","Africa/Casablanca","🇲🇦",0),
("Mozambique","MZ","MOZ","508","+258","MZN","Mozambican Metical","MT","Africa/Maputo","🇲🇿",10),
("Myanmar","MM","MMR","104","+95","MMK","Myanmar Kyat","K","Asia/Yangon","🇲🇲",10),
("Namibia","NA","NAM","516","+264","NAD","Namibian Dollar","$","Africa/Windhoek","🇳🇦",10),
("Nauru","NR","NRU","520","+674","AUD","Australian Dollar","$","Pacific/Nauru","🇳🇷",10),
("Nepal","NP","NPL","524","+977","NPR","Nepalese Rupee","₨","Asia/Kathmandu","🇳🇵",10),
("Netherlands","NL","NLD","528","+31","EUR","Euro","€","Europe/Amsterdam","🇳🇱",10),
("New Zealand","NZ","NZL","554","+64","NZD","New Zealand Dollar","$","Pacific/Auckland","🇳🇿",10),
("Nicaragua","NI","NIC","558","+505","NIO","Nicaraguan Cordoba","C$","America/Managua","🇳🇮",10),
("Niger","NE","NER","562","+227","XOF","West African CFA Franc","Fr","Africa/Niamey","🇳🇪",0),
("Nigeria","NG","NGA","566","+234","NGN","Nigerian Naira","₦","Africa/Lagos","🇳🇬",0),
("North Korea","KP","PRK","408","+850","KPW","North Korean Won","₩","Asia/Pyongyang","🇰🇵",10),
("North Macedonia","MK","MKD","807","+389","MKD","Macedonian Denar","ден","Europe/Skopje","🇲🇰",10),
("Norway","NO","NOR","578","+47","NOK","Norwegian Krone","kr","Europe/Oslo","🇳🇴",10),
("Oman","OM","OMN","512","+968","OMR","Omani Rial","ر.ع.","Asia/Muscat","🇴🇲",0),
("Pakistan","PK","PAK","586","+92","PKR","Pakistani Rupee","₨","Asia/Karachi","🇵🇰",0),
("Palau","PW","PLW","585","+680","USD","US Dollar","$","Pacific/Palau","🇵🇼",10),
("Palestine","PS","PSE","275","+970","ILS","Israeli New Shekel","₪","Asia/Gaza","🇵🇸",0),
("Panama","PA","PAN","591","+507","PAB","Panamanian Balboa","B/.","America/Panama","🇵🇦",10),
("Papua New Guinea","PG","PNG","598","+675","PGK","Papua New Guinean Kina","K","Pacific/Port_Moresby","🇵🇬",10),
("Paraguay","PY","PRY","600","+595","PYG","Paraguayan Guarani","₲","America/Asuncion","🇵🇾",10),
("Peru","PE","PER","604","+51","PEN","Peruvian Sol","S/","America/Lima","🇵🇪",10),
("Philippines","PH","PHL","608","+63","PHP","Philippine Peso","₱","Asia/Manila","🇵🇭",10),
("Poland","PL","POL","616","+48","PLN","Polish Zloty","zł","Europe/Warsaw","🇵🇱",10),
("Portugal","PT","PRT","620","+351","EUR","Euro","€","Europe/Lisbon","🇵🇹",10),
("Qatar","QA","QAT","634","+974","QAR","Qatari Riyal","ر.ق","Asia/Qatar","🇶🇦",0),
("Romania","RO","ROU","642","+40","RON","Romanian Leu","lei","Europe/Bucharest","🇷🇴",10),
("Russia","RU","RUS","643","+7","RUB","Russian Ruble","₽","Europe/Moscow","🇷🇺",10),
("Rwanda","RW","RWA","646","+250","RWF","Rwandan Franc","Fr","Africa/Kigali","🇷🇼",10),
("Saint Kitts and Nevis","KN","KNA","659","+1869","XCD","East Caribbean Dollar","$","America/St_Kitts","🇰🇳",10),
("Saint Lucia","LC","LCA","662","+1758","XCD","East Caribbean Dollar","$","America/St_Lucia","🇱🇨",10),
("Saint Vincent and the Grenadines","VC","VCT","670","+1784","XCD","East Caribbean Dollar","$","America/St_Vincent","🇻🇨",10),
("Samoa","WS","WSM","882","+685","WST","Samoan Tala","T","Pacific/Apia","🇼🇸",10),
("San Marino","SM","SMR","674","+378","EUR","Euro","€","Europe/San_Marino","🇸🇲",10),
("Sao Tome and Principe","ST","STP","678","+239","STN","Sao Tomean Dobra","Db","Africa/Sao_Tome","🇸🇹",10),
("Saudi Arabia","SA","SAU","682","+966","SAR","Saudi Riyal","ر.س","Asia/Riyadh","🇸🇦",0),
("Senegal","SN","SEN","686","+221","XOF","West African CFA Franc","Fr","Africa/Dakar","🇸🇳",0),
("Serbia","RS","SRB","688","+381","RSD","Serbian Dinar","дин.","Europe/Belgrade","🇷🇸",10),
("Seychelles","SC","SYC","690","+248","SCR","Seychellois Rupee","₨","Indian/Mahe","🇸🇨",10),
("Sierra Leone","SL","SLE","694","+232","SLE","Sierra Leonean Leone","Le","Africa/Freetown","🇸🇱",0),
("Singapore","SG","SGP","702","+65","SGD","Singapore Dollar","$","Asia/Singapore","🇸🇬",0),
("Slovakia","SK","SVK","703","+421","EUR","Euro","€","Europe/Bratislava","🇸🇰",10),
("Slovenia","SI","SVN","705","+386","EUR","Euro","€","Europe/Ljubljana","🇸🇮",10),
("Solomon Islands","SB","SLB","090","+677","SBD","Solomon Islands Dollar","$","Pacific/Guadalcanal","🇸🇧",10),
("Somalia","SO","SOM","706","+252","SOS","Somali Shilling","Sh","Africa/Mogadishu","🇸🇴",0),
("South Africa","ZA","ZAF","710","+27","ZAR","South African Rand","R","Africa/Johannesburg","🇿🇦",10),
("South Korea","KR","KOR","410","+82","KRW","South Korean Won","₩","Asia/Seoul","🇰🇷",10),
("South Sudan","SS","SSD","728","+211","SSP","South Sudanese Pound","£","Africa/Juba","🇸🇸",10),
("Spain","ES","ESP","724","+34","EUR","Euro","€","Europe/Madrid","🇪🇸",10),
("Sri Lanka","LK","LKA","144","+94","LKR","Sri Lankan Rupee","₨","Asia/Colombo","🇱🇰",10),
("Sudan","SD","SDN","729","+249","SDG","Sudanese Pound","ج.س.","Africa/Khartoum","🇸🇩",0),
("Suriname","SR","SUR","740","+597","SRD","Surinamese Dollar","$","America/Paramaribo","🇸🇷",10),
("Sweden","SE","SWE","752","+46","SEK","Swedish Krona","kr","Europe/Stockholm","🇸🇪",10),
("Switzerland","CH","CHE","756","+41","CHF","Swiss Franc","Fr","Europe/Zurich","🇨🇭",10),
("Syria","SY","SYR","760","+963","SYP","Syrian Pound","£","Asia/Damascus","🇸🇾",0),
("Taiwan","TW","TWN","158","+886","TWD","New Taiwan Dollar","$","Asia/Taipei","🇹🇼",10),
("Tajikistan","TJ","TJK","762","+992","TJS","Tajikistani Somoni","ЅМ","Asia/Dushanbe","🇹🇯",0),
("Tanzania","TZ","TZA","834","+255","TZS","Tanzanian Shilling","Sh","Africa/Dar_es_Salaam","🇹🇿",0),
("Thailand","TH","THA","764","+66","THB","Thai Baht","฿","Asia/Bangkok","🇹🇭",10),
("Timor-Leste","TL","TLS","626","+670","USD","US Dollar","$","Asia/Dili","🇹🇱",10),
("Togo","TG","TGO","768","+228","XOF","West African CFA Franc","Fr","Africa/Lome","🇹🇬",10),
("Tonga","TO","TON","776","+676","TOP","Tongan Pa'anga","T$","Pacific/Tongatapu","🇹🇴",10),
("Trinidad and Tobago","TT","TTO","780","+1868","TTD","Trinidad and Tobago Dollar","$","America/Port_of_Spain","🇹🇹",10),
("Tunisia","TN","TUN","788","+216","TND","Tunisian Dinar","د.ت","Africa/Tunis","🇹🇳",0),
("Turkey","TR","TUR","792","+90","TRY","Turkish Lira","₺","Europe/Istanbul","🇹🇷",0),
("Turkmenistan","TM","TKM","795","+993","TMT","Turkmenistani Manat","m","Asia/Ashgabat","🇹🇲",0),
("Tuvalu","TV","TUV","798","+688","AUD","Australian Dollar","$","Pacific/Funafuti","🇹🇻",10),
("Uganda","UG","UGA","800","+256","UGX","Ugandan Shilling","Sh","Africa/Kampala","🇺🇬",10),
("Ukraine","UA","UKR","804","+380","UAH","Ukrainian Hryvnia","₴","Europe/Kyiv","🇺🇦",10),
("United Arab Emirates","AE","ARE","784","+971","AED","UAE Dirham","د.إ","Asia/Dubai","🇦🇪",0),
("United Kingdom","GB","GBR","826","+44","GBP","British Pound","£","Europe/London","🇬🇧",0),
("United States","US","USA","840","+1","USD","US Dollar","$","America/New_York","🇺🇸",0),
("Uruguay","UY","URY","858","+598","UYU","Uruguayan Peso","$","America/Montevideo","🇺🇾",10),
("Uzbekistan","UZ","UZB","860","+998","UZS","Uzbekistani Som","so'm","Asia/Tashkent","🇺🇿",0),
("Vanuatu","VU","VUT","548","+678","VUV","Vanuatu Vatu","Vt","Pacific/Efate","🇻🇺",10),
("Vatican City","VA","VAT","336","+379","EUR","Euro","€","Europe/Vatican","🇻🇦",10),
("Venezuela","VE","VEN","862","+58","VES","Venezuelan Bolivar","Bs.","America/Caracas","🇻🇪",10),
("Vietnam","VN","VNM","704","+84","VND","Vietnamese Dong","₫","Asia/Ho_Chi_Minh","🇻🇳",10),
("Yemen","YE","YEM","887","+967","YER","Yemeni Rial","﷼","Asia/Aden","🇾🇪",0),
("Zambia","ZM","ZMB","894","+260","ZMW","Zambian Kwacha","ZK","Africa/Lusaka","🇿🇲",10),
("Zimbabwe","ZW","ZWE","716","+263","ZWG","Zimbabwe Gold","ZiG","Africa/Harare","🇿🇼",10),
]

def esc(s):
    if s is None or s == "":
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"

def numesc(s):
    return "NULL" if not s else f"'{s}'"

print("-- AUTO-GENERATED by generate_countries_seed.py — do not hand-edit rows below.")
print("-- Full ISO-3166 country list with calling codes, ISO-4217 currency data, and default IANA timezone.")
print(f"-- {len(COUNTRIES)} countries seeded.")
print("insert into countries (name, iso2, iso3, numeric_code, calling_code, currency_code, currency_name, currency_symbol, default_timezone, flag_emoji, sort_order) values")
rows = []
for (name, iso2, iso3, num, cc, curcode, curname, cursym, tz, flag, sort) in COUNTRIES:
    rows.append(
        f"({esc(name)}, {esc(iso2)}, {esc(iso3)}, {numesc(num)}, {esc(cc)}, {esc(curcode)}, {esc(curname)}, {esc(cursym)}, {esc(tz)}, {esc(flag)}, {sort})"
    )
print(",\n".join(rows) + "\n" + "on conflict (iso2) do update set\n"
      "  name = excluded.name, iso3 = excluded.iso3, numeric_code = excluded.numeric_code,\n"
      "  calling_code = excluded.calling_code, currency_code = excluded.currency_code,\n"
      "  currency_name = excluded.currency_name, currency_symbol = excluded.currency_symbol,\n"
      "  default_timezone = excluded.default_timezone, flag_emoji = excluded.flag_emoji,\n"
      "  sort_order = excluded.sort_order, updated_at = now();")
