import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import LogoutButton from "./LogoutButton";

export default async function DashboardPage() {
  const supabase = createClient() as any;
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  const { data: profile } = await supabase.from("profiles").select("full_name, account_code, profile_completeness_pct").eq("id", user.id).maybeSingle();
  return <main className="min-h-screen bg-sand-50 p-6"><div className="max-w-3xl mx-auto"><header className="flex items-center justify-between mb-8"><div><p className="text-xs text-ink-400">MasjidFinder account</p><h1 className="text-2xl font-semibold text-emerald-900">Assalamu alaikum, {profile?.full_name ?? user.user_metadata?.full_name ?? "there"}</h1></div><LogoutButton /></header><div className="grid gap-4 sm:grid-cols-2"><section className="rounded-2xl border border-black/10 bg-white p-6 sm:col-span-2"><p className="text-sm text-ink-600">Your session is active and your profile is saved securely.</p><p className="text-xs text-ink-400 mt-2">Account {profile?.account_code ?? "pending"} · {profile?.profile_completeness_pct ?? 0}% complete</p><div className="mt-5 flex flex-wrap gap-2"><Link href="/dashboard/profile" className="rounded-lg bg-emerald-900 px-4 py-3 text-sm font-semibold text-white">Edit profile</Link><Link href="/chat" className="rounded-lg border border-emerald-900 px-4 py-3 text-sm font-semibold text-emerald-900">Open messages</Link><Link href="/search" className="rounded-lg border border-black/10 px-4 py-3 text-sm font-semibold text-ink-700">Discover people</Link></div></section><Link href="/plans" className="rounded-xl border border-black/10 bg-white p-5 hover:border-emerald-700"><p className="text-xs font-bold uppercase tracking-[0.14em] text-gold-600">Grow your reach</p><h2 className="mt-2 font-semibold text-emerald-900">Plans and boosts</h2><p className="mt-1 text-sm text-ink-600">Explore visibility options and send an enquiry.</p></Link><Link href="/shop" className="rounded-xl border border-black/10 bg-white p-5 hover:border-emerald-700"><p className="text-xs font-bold uppercase tracking-[0.14em] text-gold-600">Community shop</p><h2 className="mt-2 font-semibold text-emerald-900">Browse Islamic goods</h2><p className="mt-1 text-sm text-ink-600">Find useful books, gifts and prayer essentials.</p></Link></div></div></main>;
}