import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import AddToCart from "./AddToCart";

export const dynamic = "force-dynamic";

export default async function ShopPage({ searchParams }: { searchParams: { category?: string } }) {
  const supabase = createClient() as any;
  const [{ data: categories }, { data: products, error }] = await Promise.all([
    supabase.from("shop_categories").select("id,name,slug").eq("is_active", true).order("sort_order"),
    supabase.from("shop_products").select("id,name,description,images,price,currency,stock,category").eq("is_active", true).gt("stock", 0).order("created_at", { ascending: false }),
  ]);
  const filtered = searchParams.category ? (products ?? []).filter((product: any) => product.category === searchParams.category) : products ?? [];
  return <main className="min-h-screen bg-sand-50 px-4 py-8 sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><Link href="/" className="text-sm font-semibold text-emerald-700">← Home</Link><Link href="/shop/cart" className="rounded-lg border border-emerald-900 px-3 py-2 text-sm font-semibold text-emerald-900">Cart</Link></div><header className="mt-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-gold-600">MasjidFinder shop</p><h1 className="mt-2 text-3xl font-semibold text-emerald-900">Useful things, thoughtfully chosen</h1><p className="mt-2 max-w-xl text-ink-600">Browse Islamic books, prayer essentials and gifts from approved sellers.</p></header><nav className="mt-6 flex gap-2 overflow-x-auto pb-2"><Link href="/shop" className="shrink-0 rounded-full border border-black/10 bg-white px-4 py-2 text-sm font-semibold">All products</Link>{(categories ?? []).map((category: any) => <Link key={category.id} href={`/shop?category=${category.slug}`} className="shrink-0 rounded-full border border-black/10 bg-white px-4 py-2 text-sm font-semibold">{category.name}</Link>)}</nav>{error ? <p className="mt-6 rounded-lg bg-red-50 p-4 text-sm text-red-800">Shop is temporarily unavailable: {error.message}</p> : <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{filtered.map((product: any) => <article key={product.id} className="flex flex-col rounded-xl border border-black/10 bg-white p-4"><div className="flex-1">{product.images?.[0] ? <img src={product.images[0]} alt={product.name} className="aspect-square w-full rounded-lg object-cover" /> : <div className="flex aspect-square items-center justify-center rounded-lg bg-sand-100 text-4xl text-emerald-900">✦</div>}<h2 className="mt-4 font-semibold text-emerald-900">{product.name}</h2><p className="mt-1 line-clamp-2 text-sm text-ink-600">{product.description || "A useful addition to your home or learning space."}</p><p className="mt-3 font-semibold text-ink-900">{product.currency} {product.price}</p></div><div className="mt-4 flex gap-2"><Link href={`/shop/${product.id}`} className="flex-1 rounded-lg border border-emerald-900 px-3 py-2 text-center text-xs font-semibold text-emerald-900">Details</Link><AddToCart product={{ id: product.id, name: product.name, price: product.price, currency: product.currency }} /></div></article>)}</section>}{!error && !filtered.length && <p className="mt-8 rounded-lg border border-black/10 bg-white p-5 text-sm text-ink-600">No products are available in this category yet.</p>}</div></main>;
}