"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export default function ChatClient({ conversationId, userId, profile }: { conversationId: string; userId: string; profile?: { full_name?: string | null; username?: string | null; profile_picture_url?: string | null; country_name?: string | null; flag_emoji?: string | null } | null }) {
  const supabase = useMemo(() => createClient(), []);
  const [messages, setMessages] = useState<any[]>([]); const [content, setContent] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [live, setLive] = useState(false); const liveRef = useRef(false); const bottomRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    let active = true;
    const loadMessages = async () => { const response = await fetch(`/api/chat?conversationId=${encodeURIComponent(conversationId)}`, { cache: "no-store" }); const result = await response.json(); if (active && response.ok) setMessages(result.messages ?? []); };
    void loadMessages();
    void fetch("/api/chat", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ conversationId }) });
    const channel = supabase.channel(`conversation:${conversationId}`, { config: { broadcast: { self: false } } }).on("postgres_changes", { event: "INSERT", schema: "public", table: "messages", filter: `conversation_id=eq.${conversationId}` }, (payload) => setMessages((current) => current.some((message) => message.id === payload.new.id) ? current : [...current, payload.new])).subscribe((status: string) => { liveRef.current = status === "SUBSCRIBED"; setLive(liveRef.current); });
    const fallback = window.setInterval(() => { if (!liveRef.current) void loadMessages(); }, 2500);
    return () => { active = false; window.clearInterval(fallback); void supabase.removeChannel(channel); };
  }, [conversationId, supabase]);
  async function sendMessage(event: React.FormEvent) { event.preventDefault(); if (!content.trim()) return; setBusy(true); setError(null); const response = await fetch("/api/chat", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ conversationId, content }) }); const result = await response.json(); setBusy(false); if (!response.ok) { setError(result.error ?? "Could not send message."); return; } setMessages((current) => current.some((message) => message.id === result.message.id) ? current : [...current, result.message]); setContent(""); }
  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages]);
  return <section className="overflow-hidden rounded-2xl border border-black/10 bg-white"><div className="flex items-center gap-3 border-b border-black/5 px-4 py-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-full bg-sand-100 text-sm font-bold text-emerald-900">{profile?.profile_picture_url ? <img src={profile.profile_picture_url} alt="" className="h-full w-full object-cover" /> : profile?.full_name?.slice(0, 1)}</div><div className="min-w-0 flex-1"><p className="truncate whitespace-nowrap text-sm font-semibold text-emerald-900">{profile?.full_name ?? "Friend"}</p><p className="truncate text-xs text-ink-400">@{profile?.username ?? "friend"} · {profile?.flag_emoji ?? ""} {profile?.country_name ?? "Connected"}</p></div><span className={`shrink-0 text-[11px] font-semibold ${live ? "text-emerald-700" : "text-ink-400"}`}>{live ? "● Live" : "Connecting..."}</span></div><div className="mb-0 max-h-[28rem] min-h-[16rem] space-y-3 overflow-y-auto bg-sand-50 p-3">{!messages.length && <p className="text-sm text-ink-400">No messages yet. Start the conversation.</p>}{messages.map((message) => <div key={message.id} className={`max-w-[82%] ${message.sender_id === userId ? "ml-auto text-right" : ""}`}><div className={`inline-block rounded-2xl px-3 py-2 text-sm ${message.sender_id === userId ? "rounded-br-sm bg-emerald-900 text-white" : "rounded-bl-sm bg-white text-ink-900 shadow-sm"}`}>{message.content}</div><p className="mt-1 text-[10px] text-ink-400">{new Date(message.created_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p></div>)}<div ref={bottomRef} /></div>{error && <p role="alert" className="px-4 pt-2 text-sm text-red-700">{error}</p>}<form onSubmit={sendMessage} className="flex gap-2 border-t border-black/5 p-3"><input value={content} onChange={(event) => setContent(event.target.value)} placeholder="Write a message" className="min-w-0 flex-1 rounded-full border border-black/10 px-4 py-3 text-sm" /><button disabled={busy} className="h-11 rounded-full bg-emerald-900 px-5 text-sm font-semibold text-white disabled:opacity-50">{busy ? "..." : "Send"}</button></form></section>;
}
